/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import aplicacion.TallerCrud;
import conceptos.Mecanico;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author andre
 */
public class VentMec extends javax.swing.JDialog {

    /**
     * Creates new form VentMec
     */
    
    public static String CodigoMec;
    public VentMec(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Menu Mecanicos");
        setSize(620,500);
        setLocationRelativeTo(null);
        Rellenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        IDP = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        Puesto = new javax.swing.JLabel();
        PuestoP = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Blanquear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMec = new javax.swing.JTable();
        Salir = new javax.swing.JButton();
        Servicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ID.setText("ID:");

        IDP.setText("Codigo");

        Nombre.setText("Nombre:");

        Puesto.setText("Puesto:");
        Puesto.setToolTipText("");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Blanquear.setText("Blanquear");
        Blanquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlanquearActionPerformed(evt);
            }
        });

        TablaMec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaMec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMecMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaMec);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Servicios.setText("Ver servicios");
        Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Blanquear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(Puesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(NombreP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                                .addComponent(PuestoP, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(229, 229, 229))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Salir)))
                            .addGap(32, 32, 32)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nuevo)
                            .addComponent(Modificar))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Borrar)
                            .addComponent(Blanquear)))
                    .addComponent(Servicios))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IDP)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nombre))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PuestoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Puesto)))
                        .addComponent(ID))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(Salir)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        String id = TallerCrud.generarIdMecanico();
        String nombre = NombreP.getText();
        String puesto = PuestoP.getText();
        Mecanico mecanico = new Mecanico(id, nombre, puesto);
        if (TallerCrud.crearMecanico(mecanico)) {
            Rellenar();
        } else{
            JOptionPane.showMessageDialog(null, "No se pudo realizar la insercion", "Error", JOptionPane.ERROR_MESSAGE);
        }
        IDP.setText("Codigo");
        PuestoP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_NuevoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int fila = TablaMec.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            TablaMec.setValueAt(IDP.getText(),fila, 0);
            TablaMec.setValueAt(NombreP.getText(),fila, 1);
            TablaMec.setValueAt(PuestoP.getText(),fila, 2);
            Mecanico mecanico = new Mecanico(IDP.getText(),NombreP.getText(),PuestoP.getText());
            TallerCrud.actualizarMecanico(mecanico);
            PuestoP.setText("");
            NombreP.setText("");

        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String ID = IDP.getText();
        TallerCrud.eliminarMecanico(ID);
        Rellenar();
        PuestoP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    private void BlanquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlanquearActionPerformed
        IDP.setText("Codigo");
        PuestoP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BlanquearActionPerformed

    private void TablaMecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMecMouseClicked
        int fila = TablaMec.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            IDP.setText(TablaMec.getValueAt(fila, 0).toString());
            NombreP.setText(TablaMec.getValueAt(fila, 1).toString());
            PuestoP.setText(TablaMec.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_TablaMecMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        VentMec.this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiciosActionPerformed
        CodigoMec = IDP.getText();
        Mecanico m = TallerCrud.buscarMecanico(VentMec.CodigoMec);
        if (m == null) {
            JOptionPane.showMessageDialog(this, "No se encontró el mecánico", "Error en el codigo", JOptionPane.ERROR_MESSAGE );
        }else{
        ServicioMec SM = new ServicioMec(VentMec.this,true);
        SM.setVisible(true);
        }
    }//GEN-LAST:event_ServiciosActionPerformed

    
    List<Mecanico>  mecanicos  = new ArrayList<>();
    private void Rellenar(){
        String XML_MECANICOS  = "Data/mecanicos.xml";
        TallerCrud.loadAll();
        mecanicos  = TallerCrud.listarMecanicos();
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
            columnas.addElement("ID");
            columnas.addElement("Nombre");
            columnas.addElement("Puesto");
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
            for(Mecanico m : mecanicos){
                Vector<String> fila = new Vector<String>();
                fila.addElement(m.getId());
                fila.addElement(m.getNombre());
                fila.addElement(m.getPuesto());
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.TablaMec.setModel(datos);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentMec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentMec dialog = new VentMec(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blanquear;
    private javax.swing.JButton Borrar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDP;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreP;
    private javax.swing.JButton Nuevo;
    private javax.swing.JLabel Puesto;
    private javax.swing.JTextField PuestoP;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Servicios;
    private javax.swing.JTable TablaMec;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
