/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import aplicacion.TallerCrud;
import conceptos.Cliente;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import util.CargadorXML;
import java.util.List;
/**
 *
 * @author andre
 */
public class VentCli extends javax.swing.JDialog {

    /**
     * Creates new form VentCli
     */
    public VentCli(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Menu Clientes");
        setSize(620,500);
        setLocationRelativeTo(null);
        Rellenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ID = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        Placa = new javax.swing.JLabel();
        PlacaP = new javax.swing.JTextField();
        Telefono = new javax.swing.JLabel();
        TelefonoP = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        CorreoP = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Blanquear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCli = new javax.swing.JTable();
        IDP = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ID.setText("ID:");

        Nombre.setText("Nombre:");

        Placa.setText("Placa:");
        Placa.setToolTipText("");

        Telefono.setText("Telefono:");

        Correo.setText("Correo:");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Blanquear.setText("Blanquear");
        Blanquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlanquearActionPerformed(evt);
            }
        });

        TablaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaCli);

        IDP.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonoP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NombreP)
                            .addComponent(PlacaP)
                            .addComponent(CorreoP)
                            .addComponent(IDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Borrar)
                            .addComponent(Nuevo))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Modificar)
                            .addComponent(Blanquear))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IDP)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlacaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Placa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Telefono)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nuevo)
                                    .addComponent(Modificar))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Borrar)
                                    .addComponent(Blanquear))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorreoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo)))
                    .addComponent(ID))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Crear, escribir y actualizar tabla
    List<Cliente>  clientes  = new ArrayList<>();
    private void Rellenar(){
        String XML_CLIENTES   = "Data/clientes.xml";
        TallerCrud.loadAll();
        clientes  = TallerCrud.listarClientes();
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
            columnas.addElement("ID");
            columnas.addElement("Nombre");
            columnas.addElement("Placa");
            columnas.addElement("Telefono");
            columnas.addElement("Correo");
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
            for(Cliente c : clientes){
                Vector<String> fila = new Vector<String>();
                fila.addElement(c.getId());
                fila.addElement(c.getNombre());
                fila.addElement(c.getPlaca());
                fila.addElement(c.getTelefono());
                fila.addElement(c.getEmail());
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.TablaCli.setModel(datos);
    }
    
    
    //Blanquear los campos
    private void BlanquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlanquearActionPerformed
        IDP.setText("Codigo");
        TelefonoP.setText("");
        CorreoP.setText("");
        PlacaP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BlanquearActionPerformed

    
    //Nuevo dato
    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        String id = TallerCrud.generarIdCliente();
        String nombre = NombreP.getText();
        String placa = PlacaP.getText();
        String telefono = TelefonoP.getText();
        String email = CorreoP.getText();
        Cliente cliente = new Cliente(id, nombre, placa, telefono, email);
        if (TallerCrud.crearCliente(cliente)) {
            Rellenar();
        } else {
            Mensaje msj = new Mensaje(VentCli.this,true);
        }
        TelefonoP.setText("");
        CorreoP.setText("");
        PlacaP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_NuevoActionPerformed

    
    //Rellenar campos con datos
    private void TablaCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCliMouseClicked
        int fila = TablaCli.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            IDP.setText(TablaCli.getValueAt(fila, 0).toString());
            NombreP.setText(TablaCli.getValueAt(fila, 1).toString());
            PlacaP.setText(TablaCli.getValueAt(fila, 2).toString());
            TelefonoP.setText(TablaCli.getValueAt(fila, 3).toString());
            CorreoP.setText(TablaCli.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_TablaCliMouseClicked

    
    //Borrar Dato
    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String ID = IDP.getText();
        TallerCrud.eliminarCliente(ID);
        Rellenar();
        TelefonoP.setText("");
        CorreoP.setText("");
        PlacaP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    
    //Modificar dato
    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int fila = TablaCli.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            TablaCli.setValueAt(IDP.getText(),fila, 0);
            TablaCli.setValueAt(NombreP.getText(),fila, 1);
            TablaCli.setValueAt(PlacaP.getText(),fila, 2);
            TablaCli.setValueAt(TelefonoP.getText(),fila, 3);
            TablaCli.setValueAt(CorreoP.getText(),fila, 4);
            TelefonoP.setText("");
            CorreoP.setText("");
            PlacaP.setText("");
            NombreP.setText("");
            
        }
    }//GEN-LAST:event_ModificarActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentCli dialog = new VentCli(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blanquear;
    private javax.swing.JButton Borrar;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField CorreoP;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDP;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreP;
    private javax.swing.JButton Nuevo;
    private javax.swing.JLabel Placa;
    private javax.swing.JTextField PlacaP;
    private javax.swing.JTable TablaCli;
    private javax.swing.JLabel Telefono;
    private javax.swing.JTextField TelefonoP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
