/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ventanas;

import aplicacion.TallerCrud;
import conceptos.Cliente;
import conceptos.Servicio;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import util.CargadorXML;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author andre
 */
public class VentServ extends javax.swing.JDialog {

    /**
     * Creates new form VentServ
     */
    public VentServ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Menu Clientes");
        setSize(620,500);
        setLocationRelativeTo(null);
        Rellenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JLabel();
        IDP = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        Precio = new javax.swing.JLabel();
        PrecioP = new javax.swing.JTextField();
        Nuevo = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        Blanquear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaServ = new javax.swing.JTable();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ID.setText("ID:");

        IDP.setText("Codigo");

        Nombre.setText("Nombre:");

        Precio.setText("Precio:");
        Precio.setToolTipText("");

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Blanquear.setText("Blanquear");
        Blanquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlanquearActionPerformed(evt);
            }
        });

        TablaServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaServMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaServ);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Borrar)
                    .addComponent(Nuevo))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificar)
                    .addComponent(Blanquear))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NombreP)
                                .addComponent(PrecioP)
                                .addComponent(IDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(229, 229, 229))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Salir)))
                    .addGap(38, 38, 38)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuevo)
                    .addComponent(Modificar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Borrar)
                    .addComponent(Blanquear))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(IDP)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Nombre))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PrecioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Precio)))
                        .addComponent(ID))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                    .addComponent(Salir)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        String id = TallerCrud.generarIdServicio();
        String nombre = NombreP.getText();
        BigDecimal precio = null;
        try {
            precio = new BigDecimal(PrecioP.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido", "Error de valor", JOptionPane.ERROR_MESSAGE);
        }

        Servicio servicio = new Servicio(id, nombre, precio);
        if (TallerCrud.crearServicio(servicio)) {
            Rellenar();
        }
        PrecioP.setText("");
        NombreP.setText("");
        IDP.setText("Codigo");
    }//GEN-LAST:event_NuevoActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        int fila = TablaServ.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            TablaServ.setValueAt(IDP.getText(),fila, 0);
            TablaServ.setValueAt(NombreP.getText(),fila, 1);
            TablaServ.setValueAt(PrecioP.getText(),fila, 2);
            PrecioP.setText("");
            NombreP.setText("");

        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        String ID = IDP.getText();
        TallerCrud.eliminarServicio(ID);
        Rellenar();
        PrecioP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BorrarActionPerformed

    private void BlanquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlanquearActionPerformed
        IDP.setText("Codigo");
        PrecioP.setText("");
        NombreP.setText("");
    }//GEN-LAST:event_BlanquearActionPerformed

    private void TablaServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaServMouseClicked
        int fila = TablaServ.getSelectedRow(); // obtener la fila seleccionada
        if (fila >= 0) {
            // Obtener los valores de la fila y asignarlos a los labels
            IDP.setText(TablaServ.getValueAt(fila, 0).toString());
            NombreP.setText(TablaServ.getValueAt(fila, 1).toString());
            PrecioP.setText(TablaServ.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_TablaServMouseClicked

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        VentServ.this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    
    List<Servicio>  servicios  = new ArrayList<>();
    private void Rellenar(){
        String XML_SERVICIOS  = "Data/servicios.xml";;
        TallerCrud.loadAll();
        servicios  = TallerCrud.listarServicios();
            //Columnas de la tabla
            Vector<String> columnas = new Vector<String>();
            columnas.addElement("ID");
            columnas.addElement("Nombre");
            columnas.addElement("Precio");
            //Filas de la tabla
            Vector<Vector> filas = new Vector<Vector>();
            for(Servicio s : servicios){
                Vector<String> fila = new Vector<String>();
                fila.addElement(s.getId());
                fila.addElement(s.getNombre());
                fila.addElement(s.getPrecio().toString());
                filas.addElement(fila);
            }
            DefaultTableModel datos = new DefaultTableModel(filas,columnas);
            this.TablaServ.setModel(datos);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentServ dialog = new VentServ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blanquear;
    private javax.swing.JButton Borrar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDP;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreP;
    private javax.swing.JButton Nuevo;
    private javax.swing.JLabel Precio;
    private javax.swing.JTextField PrecioP;
    private javax.swing.JButton Salir;
    private javax.swing.JTable TablaServ;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
